# Generated by Django 2.0.3 on 2018-03-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_no', models.TextField(max_length=30)),
                ('prd_nm', models.TextField(max_length=500)),
                ('prd_img', models.ImageField(upload_to='')),
                ('content', models.TextField(max_length=1000)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
