# Generated by Django 2.0.3 on 2018-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180403_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_img',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/product'),
        ),
    ]
