# Generated by Django 2.0.3 on 2018-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180416_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_img',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/product'),
        ),
    ]
